# Workflow for deploying Vite, React, and TypeScript project to GitHub Pages
name: Deploy Vite React TypeScript App to GitHub Pages

on:
  # Runs on pushes to the main branch
  push:
    branches: ["main"]

  # Allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the LTS version of Node.js

      # Step 3: Install dependencies and build
      - name: Install and Build
        run: |
          npm install
          npm run build
        working-directory: ./strigsys.company.page # Set this to where your package.json is located


      # Step 4: Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Upload the build output directory

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
